send_key:
  name: Send Key(s)
  description: Sends one or more specific key commands to a Hisense TV.
  fields:
    entity_id:
      name: Target TV
      example: media_player.hisense_tv_livingroom
      description: The entity ID of the Hisense TV to send the key(s) to (e.g., media_player.hisense_tv_wohnzimmer).
      required: true
      selector:
        entity:
          domain: media_player # Oder switch, je nachdem welche Entität du ansprechen willst
          integration: hisense_tv
    key:
      name: Key(s)
      description: The key command(s) to send. Can be a single key or a list of keys.
      required: true
      example: POWER
      selector:
        select:
          multiple: true
          options:
            - label: Power
              value: POWER
            - label: Volume Up
              value: VOLUMEUP
            - label: Volume Down
              value: VOLUMEDOWN
            - label: Mute
              value: MUTE
            - label: Channel Up
              value: CHANNELUP
            - label: Channel Down
              value: CHANNELDOWN
            - label: Home
              value: HOME
            - label: Menu
              value: MENU
            - label: Returns (Back)
              value: RETURNS
            - label: Exit
              value: EXIT
            - label: Source
              value: SOURCE
            - label: Info
              value: INFO
            - label: Red Button
              value: RED
            - label: Green Button
              value: GREEN
            - label: Yellow Button
              value: YELLOW
            - label: Blue Button
              value: BLUE
            - label: Up Arrow
              value: UP
            - label: Down Arrow
              value: DOWN
            - label: Left Arrow
              value: LEFT
            - label: Right Arrow
              value: RIGHT
            - label: OK
              value: OK
            - label: Play
              value: PLAY
            - label: Pause
              value: PAUSE
            - label: Stop
              value: STOP
            - label: Back (rewind)
              value: BACK
            - label: Forward (fast forward)
              value: FORWARDS
            - label: Record
              value: RECORD
            - label: Number 0
              value: '0'
            - label: Number 1
              value: '1'
            - label: Number 2
              value: '2'
            - label: Number 3
              value: '3'
            - label: Number 4
              value: '4'
            - label: Number 5
              value: '5'
            - label: Number 6
              value: '6'
            - label: Number 7
              value: '7'
            - label: Number 8
              value: '8'
            - label: Number 9
              value: '9'
            # Füge hier weitere Keys hinzu

send_channel:
  name: Send Channel
  description: Sends a channel number to a Hisense TV by sending an EXIT command first, then individual digits.
  fields:
    entity_id:
      name: Target TV
      description: The entity ID of the Hisense TV to send the channel to.
      required: true
      selector:
        entity:
          domain: media_player
          integration: hisense_tv
    channel:
      name: Channel Number
      description: The channel number to send (e.g., 1, 10, 101).
      required: true
      example: 101
      selector:
        number:
          min: 0
          max: 9999 # Max. Kanalnummer nach Bedarf anpassen

launch_app:
  name: Launch Application
  description: Launches an application on the Hisense TV.
  fields:
    entity_id:
      name: Target TV
      description: The entity ID of the Hisense TV to launch the app on.
      required: true
      selector:
        entity:
          domain: media_player
          integration: hisense_tv
    app_name:
      name: Application Name
      description: The name of the application to launch (e.g., "youtube", "netflix").
      required: true
      example: "youtube"
      selector:
        text:

send_text:
  name: Send Text
  description: Sends a text string to the Hisense TV.
  fields:
    entity_id:
      name: Target TV
      description: The entity ID of the Hisense TV to send the text to.
      required: true
      selector:
        entity:
          domain: media_player
          integration: hisense_tv
    text:
      name: Text
      description: The text string to send.
      required: true
      example: "Hello World"
      selector:
        text: